name: Release
on:
  push:
    branches:
      - main
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest]
    runs-on: ${{ matrix.platform }}
    env:
        pwd: ${{ secrets.ZIP_PWD }}  
        opt: zip  
        source: ${{ github.workspace }}/coder/src-tauri/target/release/bundle
        destination: ${{ github.workspace }}/bundle.zip
    steps:
      - uses: actions/checkout@v4
# url中使用https://kuaileniu:password@的格式是可以成功下载的
      # - name: Download private repo
      #   run: git clone https://kuaileniu:${{ secrets.ROREVER_GITHUB_TOKEN }}@github.com/kuaileniu/coder.git

# url中不加用户名时，默认是使用本repo的用户名，也可以成功clone下来   
      - name: Download private repo
        run: |
          echo "workspace----------------------------------------------------------------"
          echo "${{ github.workspace }}"
          cd ${{ github.workspace }}

          git clone https://${{ secrets.ROREVER_GITHUB_TOKEN }}@github.com/kuaileniu/coder.git

      - name: Display structure of downloaded files
        run: ls -R
      - name: Display cloud drive
        run: |
            echo "coder下的文件"
            ls  ${{ github.workspace }}/coder
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Install frontend dependencies
        run: |
              cd  ${{ github.workspace }}/coder

              pnpm install --no-frozen-lockfile

      - name: Build and release
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.ROREVER_GITHUB_TOKEN }}
          projectPath: coder 
        with:
          tagName: v__VERSION__
          releaseName: v__VERSION__
          releaseDraft: true
      
      - name: Download zip(archiver) repo and make zip package
      # git clone https://${{ secrets.ROREVER_GITHUB_TOKEN }}@github.com/kuaileniu/archiver.git
        run: |
          cd ${{ github.workspace }} 

          echo "Download当前位置"
          pwd
          
          git clone --branch v1.0.0 --single-branch https://${{ secrets.ROREVER_GITHUB_TOKEN }}@github.com/kuaileniu/archiver.git
          cd ${{ github.workspace }}/archiver
          
          echo "当前位置,期望是    xxx/archiver"
          pwd
          echo "archiver目录下的文件"
          ls
          go env -w GOPRIVATE="github.com/kuaileniu"
          git config --global url."https://kuaileniu:${{ secrets.ROREVER_GITHUB_TOKEN }}@github.com".insteadOf "https://github.com"
          go mod tidy
          go run main.go

      - name: Upload execution
        uses: actions/upload-artifact@v4
        if: always()
        with:
          # zip压缩包的名称为 action1.1.zip(使用的go module 默认名称)
          # (若干多个build时，此名称相同，则合并打包到一个zip中)
          name: elf_${{ runner.os }}
          # 0最低，9最高
          compression-level: 0
          # 将 action打包到 action1.1.zip中并把 action1.1.zip 上传到github的本次action的Artifacts下
          #path: ${{ github.workspace }}/coder/src-tauri/target/release/bundle/
          path: ${{ github.workspace }}/bundle.zip
 